thegoodparty/gp-webapp

app/(landing)/elections/position/[...loc]/components/CtaBanner.js
Adjusted CTA Copy https://goodparty.atlassian.net/jira/software/projects/WEB/issues/WEB-1670
=> WEB-1670 - Adjusted CTA copy

app/(candidate)/dashboard/funding/components/CampaignFundingPage.js
https://goodparty.atlassian.net/browse/WEB-1503
=> WEB-1503 - Updated copy

app/(landing)/elections/position/[...loc]/components/Hero.js
https://goodparty.atlassian.net/browse/WEB-1671
=> WEB-1671 - Updated sm alignment and copy for link

app/(candidate)/dashboard/content/components/ContentPage.js
https://goodparty.atlassian.net/browse/WEB-1547
=> WEB-1546 - updated copy and added logo

app/(candidate)/dashboard/content/components/NewContentFlow.js
https://goodparty.atlassian.net/browse/WEB-1546
=> WEB-1546 - updated button copy

app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CustomOfficeModal.js
=> [WEB-1699] - Updated copy

app/(candidate)/onboarding/[slug]/[step]/components/RunForOfficeStep.js
https://goodparty.atlassian.net/browse/WEB-1640
https://github.com/thegoodparty/gp-webapp/assets/496983/c1e6a115-7dff-4273-9f68-95970d82ce6b
=> [WEB-1640] - Added helper tooltip

app/(company)/work-with-us/components/JobPage.js
=> [WEB-1729] - Added padding to injected <p> tags

app/shared/layouts/navigation/LeftSide.js
=> [WEB-1731] - updated menu item labels

app/(entrance)/login/components/LoginPage.js, app/shared/inputs/IsValidPassword.js, app/shared/inputs/PasswrodInput.js, helpers/userHelper.js, package-lock.json, package.json
https://goodparty.atlassian.net/browse/WEB-1692
https://github.com/thegoodparty/gp-webapp/assets/496983/748721d1-b20b-4dca-8a8c-6d3fe5de6c3d
=> [WEB-1692] - updated password format requirements

app/(company)/team/components/Interns.js, app/(company)/team/components/Team.js, app/(company)/team/components/TeamSection.js
https://goodparty.atlassian.net/browse/WEB-1767
=> [WEB-1767] - Made team updates

app/(landing)/run-for-office/components/GetStartedCTA.js, app/(landing)/run-for-office/components/Hero.js, app/(landing)/run-for-office/components/Pricing.js, app/(landing)/run-for-office/components/ProTools.js, app/(landing)/run-for-office/components/RunCampaignButton.js, app/(landing)/run-for-office/components/StartedBottom.js, app/(landing)/run-for-office/components/WhatIsCampaign.js
https://goodparty.atlassian.net/browse/WEB-1730
=> [WEB-1730] - Changed all button and link labels

app/(landing)/elections/position/[...loc]/components/PositionDetails.js, app/(landing)/elections/position/[...loc]/components/PositionsListItem.js
https://goodparty.atlassian.net/browse/WEB-1725
=> [WEB-1725] - Made list of positions length dynamic

app/(candidate)/dashboard/details/components/OfficeSection.js, app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/ZipChanger.js, app/shared/typography/H4.js, app/shared/utils/Modal.js
https://goodparty.atlassian.net/browse/WEB-1696
https://github.com/thegoodparty/gp-webapp/assets/496983/414400d8-4a16-4401-a91e-e137fcc4e9e9
**DO NOT MERGE WITHOUT COMPANION API PR!!**
Companion API PR: https://github.com/thegoodparty/tgp-api/pull/171
=> [WEB-1696] - Races group by year implementation

app/admin/candidates/components/AdminCandidatesPage.js
https://goodparty.atlassian.net/browse/WEB-1805
=> [WEB-18095] - Changed column display value

app/admin/candidates/components/AdminCandidatesPage.js
https://goodparty.atlassian.net/browse/WEB-1806
=> [WEB-1806] - Moved columns in admin candidates table and added them to CSV

app/admin/candidates/components/AdminCandidatesPage.js, app/admin/victory-path/[slug]/components/AdminVictoryPathPage.js, app/admin/victory-path/[slug]/components/IsVerifiedSelect.js, app/admin/victory-path/[slug]/components/ProFieldsSection.js, app/admin/victory-path/[slug]/page.js
https://goodparty.atlassian.net/browse/WEB-1807
Makes the `isVerified` column an enumeration of `null/true/false` w/ `Review/Yes/No` as the mapped UX display values.
Companion API PR: https://github.com/thegoodparty/tgp-api/pull/172
=> [WEB-1807] - dropdown for verified column

app/(landing)/ads2023/components/DiscordSection.js, app/shared/layouts/constants.js, app/shared/layouts/navigation/LeftSide.js, app/shared/utils/Callout.js
https://goodparty.atlassian.net/browse/WEB-1713
=> [WEB-1713] - updated url across codebase

app/(entrance)/reset-password/page.js, app/admin/candidates/components/AdminCandidatesPage.js, app/admin/victory-path/[slug]/components/ProFieldsSection.js
https://goodparty.atlassian.net/browse/WEB-1796
*Also fixes url-encoded email characters breaking password-reset flow
Companion API PR: https://github.com/thegoodparty/tgp-api/pull/174
=> [WEB-1796] - Adds "Verified Date" column to admin

app/admin/candidates/components/AdminCandidatesPage.js
https://goodparty.atlassian.net/browse/WEB-1837
=> [WEB-1837] - adds zip column to admin campaign table and CSV export

app/admin/candidates/components/AdminCandidatesPage.js
https://goodparty.atlassian.net/browse/WEB-1841
=> [WEB-1841] - adds office level columns to table and csv

app/admin/candidates/components/AdminCandidatesPage.js
https://goodparty.atlassian.net/browse/WEB-1838
=> [WEB-1838] - Website column

app/(candidate)/dashboard/resources/components/ResourcesPage.js, app/(candidate)/dashboard/resources/page.js, gpApi/gpFetch.js
https://goodparty.atlassian.net/browse/WEB-1818
Made some of the code paths here a bit more resilient since I was getting 500s on my local env w/ incomplete data..
=> [WEB-1818] - Removes duplicate listing in Resource Library

app/(landing)/academy-webinar/components/GraduateSpotlight.js, app/(landing)/academy-webinar/components/Graduates.js, app/(landing)/academy-webinar/components/Hero.js, app/(landing)/academy-webinar/components/Hero2.js, app/(landing)/academy-webinar/components/WhyAcademy.js, app/(landing)/academy/components/AcademyPage.js, app/(landing)/academy/components/AcademySignUpModal/AcademyModalSignUpButton.js, app/(landing)/academy/components/AcademySignUpModal/AcademySignUpModal.js, app/(landing)/academy/components/AcademySignUpModal/AcademySignUpModalProvider.js, app/(landing)/academy/components/AcademySignUpModal/useAcademySignUpModalState.js, app/(landing)/academy/page.js, app/(landing)/elections/components/ElectionsPage.js, app/shared/buttons/WarningButton.js, app/shared/utils/AnimatedEllipsis.js, app/shared/utils/HubSpotForm.js
https://goodparty.atlassian.net/browse/WEB-1876
=> [WEB-1876] - Adds HubSpot Form Modal to buttons

app/shared/buttons/BaseButton.js, app/shared/buttons/ErrorButton.js, app/shared/buttons/InfoButton.js, app/shared/buttons/PrimaryButton.js, app/shared/buttons/SecondaryButton.js, app/shared/buttons/SuccessButton.js, app/shared/buttons/WarningButton.js, app/shared/layouts/navigation/NavDropdown.js, package.json
Also adds a `start-local` npm script for building an optimized (prod) build for local perf testing.
=> Makes code for buttons ship to client

app/shared/layouts/PageWrapper.js, app/shared/layouts/constants.js, app/shared/layouts/footer/Footer.js, app/shared/layouts/footer/components/FooterButtonLink.js, app/shared/layouts/footer/components/FooterExternalLink.js, app/shared/layouts/footer/components/FooterLinkWrapper.js
https://goodparty.atlassian.net/browse/WEB-1995
=> [WEB-1995] - Adds id attribs and cleans up JSX for Footer

app/(entrance)/login/components/LoginPage.js
https://goodparty.atlassian.net/browse/WEB-1982
=> [WEB-1982] - login copy change

app/(company)/team/components/Funding.js, app/(company)/team/components/LeadingTheMovement.js, app/(company)/team/components/OurImpact.js, app/(company)/team/components/TeamHero.js, app/(company)/team/components/TeamMembersSection.js, app/(company)/team/components/TeamMilestones.js, app/(company)/team/components/TeamsPage.js
https://goodparty.atlassian.net/browse/WEB-2088
=> [WEB-2088] - Team page clean up

app/(candidate)/dashboard/questions/components/issues/IssuesSearch.js
Fixes this behavior:
https://github.com/thegoodparty/gp-webapp/assets/496983/7f09f04a-bbb5-4ec2-be89-c9de663db19b
=> [WEB-1799] - Fixes filter input from not really being cleared after blur from the input

app/(candidate)/dashboard/questions/components/issues/IssuesList.js
One more small change for this bug... 🤞
=> [WEB-1799] - sigh

app/(candidate)/dashboard/pro-sign-up/page.js, app/(candidate)/dashboard/pro-sign-up/purchase-redirect/components/PurchaseRedirectPage.js, app/(candidate)/dashboard/pro-sign-up/success/page.js, app/(candidate)/dashboard/shared/DashboardMenu.js, app/(candidate)/dashboard/shared/candidateAccess.js, app/(entrance)/login/components/LoginPage.js, app/(entrance)/login/components/SocialRegisterButtons.js, app/(entrance)/login/page.js, app/(entrance)/set-name/components/SocialLoginButtons.js, app/admin/campaign-statistics/components/CampaignStatisticsPage.js, app/admin/campaign-statistics/page.js, app/api/v1/entrance/[loginType]/route.js, app/api/v1/entrance/logout/route.js, app/shared/layouts/navigation/ProfileDropdown.js, app/shared/user/handleLogOut.js, app/sitemaps/sitemap.js, gpApi/gpFetch.js, gpApi/index.js, helpers/cookieHelper.js, helpers/getRedirects.js, helpers/handleApiRequestRewrite.js, helpers/handlePathCapitalizationRedirect.js, helpers/handlePathRedirect.js, helpers/tokenCookie.js, helpers/userServerHelper.js, middleware.js, next.config.js
Companion API app: https://github.com/thegoodparty/tgp-api/pull/201
=> [WEB-2360] - Next rewrite middleware for server-side, secure cookie management

vercel.json
companion API PR: https://github.com/thegoodparty/tgp-api/pull/214
=> [WEB-2248][WEB-2490][WEB-2253] - Vercel config for daily cron job

app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/components/ServiceAgreementPage.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/components/TermAndTerminationText.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/page.js, app/(candidate)/onboarding/[slug]/[step]/components/LegalStatements.js, app/(candidate)/onboarding/[slug]/[step]/components/PledgeStep.js, app/shared/acknowledgements/AcknowledgementQuestion.js, app/shared/acknowledgements/AcknowledgementQuestionBody.js, app/shared/acknowledgements/AcknowledgementTitleBar.js, app/shared/alerts/AlertIcon.js, app/shared/alerts/ErrorAlert.js, app/shared/alerts/InfoAlert.js, app/shared/alerts/StyledAlert.js
Ticket: https://goodparty.atlassian.net/browse/WEB-2417
=> [WEB-2417] - Service Agreement View

app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js, app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js
Companion API PR: https://github.com/thegoodparty/tgp-api/pull/220
=> [WEB-2474] - Prepopulates document upload if file is already uploaded

app/admin/candidates/components/AdminCandidatesTable.js
API PR: https://github.com/thegoodparty/tgp-api/pull/222
=> [WEB-2535] - lastVisited and createdAt fix

app/(user)/profile/components/AccountSettingsSection.js, app/(user)/profile/components/SubscriptionPendingCancellationAlert.js, app/(user)/profile/page.js, helpers/dateHelper.js
API PR: https://github.com/thegoodparty/tgp-api/pull/223
=> [WEB-2473] - Pending cancellation handling

app/(company)/team/page.js
API PR: https://github.com/thegoodparty/tgp-api/pull/224
=> [WEB-2169] - Preserve ordering in Team Members

app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js, app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js
File upload limit PR: https://github.com/thegoodparty/tgp-api/pull/226
=> [WEB-2656] - Message to user file upload limit

app/(candidate)/onboarding/[slug]/[step]/components/LegalStatements.js, app/(company)/terms-of-service/page.js, app/shared/FullContentPage.js, app/shared/layouts/footer/Footer.js, helpers/fetchContent.js
API PR: https://github.com/thegoodparty/tgp-api/pull/225
=> [WEB-2045] - new Terms of Service page and linking

app/(candidate)/browsing-final/components/BrowsingFinalPage.js, app/(candidate)/browsing-final/page.js, app/(candidate)/onboarding/[slug]/[step]/components/PledgeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, app/(user)/profile/components/AccountSettingsButton.js, app/shared/utils/handleDemoAccountDeletion.js
companion API PR: https://github.com/thegoodparty/tgp-api/pull/232
=> [WEB-2726] - browsing copy change and bug fixes

app/(candidate)/dashboard/pro-sign-up/committee-check/page.js, app/(candidate)/dashboard/pro-sign-up/page.js, app/(candidate)/dashboard/pro-sign-up/purchase-redirect/page.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/page.js, app/(candidate)/dashboard/pro-sign-up/success/page.js, app/(candidate)/dashboard/shared/restrictDemoAccess.js, app/(candidate)/dashboard/upgrade-to-pro/components/UpdateToProPage.js, app/shared/alerts/StyledAlert.js, app/shared/utils/AlertDialog.js
Also corrects use of dynamic Tailwind classes in the alert banner per: https://stackoverflow.com/a/74959709/282250
=> [WEB-2727] - dialog for demo-pro upgrade

app/shared/layouts/navigation/NavDropdown.js, app/shared/layouts/navigation/NavigationProvider.js
This PR includes: [WEB-2753: Global Navigation - Rework Nav dropdown "For Candidates"](https://goodparty.atlassian.net/browse/WEB-2753) and [Global Nav - Add "Get Stickers" to the dropdown menu "For Voters"](https://goodparty.atlassian.net/browse/WEB-2748). It updates the Global Nav menus to have a few new links, and also updates the icons to use the rounded material icons to match the designs. 
| Before  | After |
| ------------- | ------------- |
|<img width="200" alt="Screenshot 2024-08-21 at 9 16 28 AM" src="https://github.com/user-attachments/assets/0f91c954-5b0a-4850-a5fb-48edc9691280"><img width="200" alt="Screenshot 2024-08-21 at 9 16 33 AM" src="https://github.com/user-attachments/assets/0b1a2b7a-87ff-41da-b0f4-86df2358da06"><img width="200" alt="Screenshot 2024-08-21 at 9 16 …
=> WEB-2753, WEB-2748: Update nav dropdowns

app/(candidate)/dashboard/components/AlertSection.js, app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js, app/shared/inputs/HiddenFileUploadInput.js, gpApi/index.js
API companion PR: https://github.com/thegoodparty/tgp-api/pull/246
=> [WEB-2817] - Fix File Upload Limit

app/blog/article/[slug]/components/ArticleFaqs.js, app/blog/article/[slug]/components/Banner.js, app/blog/article/[slug]/components/BlogArticlePage.js, app/blog/article/[slug]/components/HighlightedContent.js
Small updates for the Blog. 
- Updated the Article FAQs section on Blog Article page to pull from new field in Contentful.
- Updated "End Blurb" field on Blog Article to be a rich text field.
- Updated the banners on Blog Articles to have a larger image that takes up half the banner
|Banner Before|Banner After|
|-|-|
|<img width="804" alt="Screenshot 2024-09-12 at 5 32 02 PM" src="https://github.com/user-attachments/assets/aafa9d76-49be-4336-a6e2-2a351252cc0e">|<img width="871" alt="Screenshot 2024-09-12 at 5 31 39 PM" src="https://github.com/user-attachments/assets/efba63ba-1fa5-4df3-8893-aa4b15da70d0">| 
**Testing info in [JIRA ticket](https://goodparty.atlassian.net/browse/WEB-2862)**
=> WEB-2862: Blog: Content Updates

app/blog/article/[slug]/components/Banner.js
Updates the Blog Banner to prevent images from sizing larger than their native sizes.
=> WEB-2909: Restrict banner image size if image sizes are present from Contentful

app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlow.js, package-lock.json, package.json
Changes were needed in order for the slack notification to have the needed information that's triggered on tgp-api
=> Slack notification schedule campaign

app/blog/article/[slug]/components/Banner.js
Added the Banner's ID specified in Contentful to the link, to get tracked properly.
=> WEB-2963: Blog Article Banners' IDs/Class Names Not Working

app/(candidate)/dashboard/content/components/TemplatesList.js, app/(candidate)/dashboard/plan/components/CampaignPlanSection.js, app/shared/utils/TogglePanel.js, helpers/fullStoryHelper.js
Adds element tracking attributes for AI content generation functionality. Also adds a helper function to make setting tracking attributes simpler and repeatable.
=> WEB-3063: Add tracking for KPI: Content pieces generated

app/(candidate)/dashboard/campaign-manager/components/CampaignManagerPage.js
added a track event call to the Campaign Manger chatbot
=> WEB-3064: Add tracking for KPI: Campaign manager chatbot usage

app/(candidate)/dashboard/components/contactMethods/LogProgress.js, app/(candidate)/dashboard/plan/components/PlanActions.js, app/(candidate)/dashboard/resources/components/ResourcesWrapper.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlow.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowStep4.js, app/(candidate)/onboarding/[slug]/[step]/components/CompleteStep.js, app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/PartyStep.js, app/(candidate)/onboarding/[slug]/[step]/components/PledgeStep.js, app/shared/scripts/UserSnapScript.js
More Fullstory tracking attributes on elements
=> WEB-3062, WEB-3060, WEB-3059: Add more tracking attributes and events

app/shared/layouts/navigation/RightSideMobile.js
Fixes an iOS Safari rendering issue with the Login/Signup/etc links at the bottom of the mobile sidebar nav.
=> WEB-2857: The Login, Signup and Get Campaign Tools buttons are inside the Menu

app/(candidate)/dashboard/components/contactMethods/MethodRow.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlow.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowStep0.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowStep1.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowStep2.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowStep4.js, app/(candidate)/dashboard/voter-records/[type]/components.js/VoterFileDetailPage.js, app/(candidate)/dashboard/voter-records/components/CustomVoterAudienceFilters.js, app/(candidate)/dashboard/voter-records/components/VoterFileTypes.js
Adds an instructions step before the Schedule Text Campaign flow [WEB-3089](https://goodparty.atlassian.net/browse/WEB-3089)
Adds a new `audience_request` field to the Audience Targeting step of the scheduling flow [WEB-3086](https://goodparty.atlassian.net/browse/WEB-3086)
Before:
After:
[WEB-3089]: https://goodparty.atlassian.net/browse/WEB-3089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3086]: https://goodparty.atlassian.net/browse/WEB-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEB-3089, WEB-3086: Add a "How this works" screen to the texting flow, "Who would you like to text?" includes a free text field

app/admin/victory-path/[slug]/components/AdditionalFieldsSection.js, app/admin/victory-path/[slug]/components/AdminVictoryPathPage.js, app/shared/inputs/RenderInputField.js, app/shared/scripts/UserSnapScript.js
Fixes a few smaller bugs that could have been contributing to two bug tickets: https://goodparty.atlassian.net/browse/WEB-3126, https://goodparty.atlassian.net/browse/WEB-2978
**Note:** I wasn't able to reproduce the bug myself, but found some errors on the page that could have been related.
- Removes two duplicated inputs
- Fixed some errors with passing `null` values to input elements
- Fixed an error with some elements using `class` instead of `className` 
- Fixed error with an `InputLabelProps` attribute on a `Select`
- Also adds the fullstory session URL to usersnap submissions for better bug digging in the future
=> WEB-3126, WEB-2978: Bug fixes for /admin/victory-path/

app/(candidate)/dashboard/components/DashboardPage.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlow.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowAudienceStep.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowBudgetStep.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowComplete.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowImageStep.js, app/(candidate)/dashboard/voter-records/[type]/components.js/ScheduleFlowScheduleStep.js, app/(candidate)/dashboard/voter-records/components/CustomVoterAudienceFilters.js
Updates schedule flow to make sure each step keeps the previously set state when navigating back. 
**NOTE:** Does not change the Script selection part of the flow here, to avoid conflicts with other work
=> WEB-3088: Ensure users don't lose information when navigating back in the texting flow

app/(candidate)/dashboard/content/components/InputFieldsModal.js, app/(candidate)/dashboard/content/components/MyContent.js, app/shared/scripts/UserSnapScript.js
Adds some extra Fullstory tracking around AI Content generation. 
- Adds tracking attributes to the Additional Info submit button
- Adds a custom event to the event handler that triggers the actual content generation call
- Also put in a fix for adding the FS session url to Usersnap submissions
=> WEB-3114: Update Generate AI Content tracking - Add modal submit

app/(candidate)/dashboard/voter-records/[type]/components/ScheduleFlow.js, app/candidates/components/map/Filters.js
Frontend component of https://github.com/thegoodparty/tgp-api/pull/291. 
`voterFileUrl` is built on the backend now, so doesn't need to be sent from here anymore.
=> WEB-3209: Custom Voter File not Saving correctly

app/(candidate)/onboarding/account-type/page.js, app/(candidate)/onboarding/browsing/components/BrowsingPage.js, app/(candidate)/onboarding/managing/candidate-lookup/components/CandidateLookupPage.js, app/(entrance)/sign-up/page.js, app/shared/layouts/PageWrapper.js, app/shared/layouts/navigation/LeftSide.js, app/shared/layouts/navigation/RightSide.js, app/shared/layouts/navigation/RightSideMobile.js, app/shared/utils/Snackbar.js, app/shared/utils/handleDemoAccountDeletion.js
The ticket isn't completely accurate, I commented what's going on here: https://goodparty.atlassian.net/browse/WEB-3206?focusedCommentId=14621.
- This hides the marketing nav links when on the `/profile` page. The user in the ticket didn't realize those links were app feature links
=> WEB-3206: Logged in candidate is taken to Settings when navigating to marketing links

app/(candidate)/dashboard/voter-records/[type]/components/CloseConfirmModal.js, app/(candidate)/dashboard/voter-records/[type]/components/ScheduleFlow.js, app/shared/utils/Modal.js, helpers/objectHelper.js
This adds a confirmation modal when closing out of a Text or Phone campaign scheduling flow.
=> WEB-3094: Text scheduling clickout confirmation

app/(candidate)/onboarding/managing/candidate-lookup/components/CandidateLookupPage.js, app/(candidate)/onboarding/managing/candidate-lookup/page.js
https://goodparty.atlassian.net/browse/WEB-3278
=> [WEB-3278] - Update error UX for CMs

app/admin/campaign-statistics/components/SearchForm.js, app/admin/campaign-statistics/page.js, app/admin/candidates/components/AdminCandidatesTable.js, app/shared/inputs/RenderInputField.js, helpers/objectHelper.js
Adds a P2V status filter to the admin campaigns view
=> WEB-3258: Add p2v status filter to admin campaigns

app/candidates/components/winners/FilteredWinnerList.js, app/candidates/components/winners/WinnerFilters.js, app/candidates/components/winners/WinnerListSection.js, app/shared/hooks/useMapCampaigns.js
Fixes a few issues for the campaign map winner's list section.
- Fixes the count of winners being off
- Fixes the filters not accurately reflecting the filters being used
- Fixes an issue with too many pagination dots displaying when there are more than a few hundred winners
Pagination Before:
Pagination After:
=> WEB-3268: Fix map winners list bugs

app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js, app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js, app/(candidate)/dashboard/pro-sign-up/components/ProSignUpPage.js, app/(candidate)/dashboard/shared/AsyncValidationIcon.js, app/(candidate)/dashboard/shared/InputHelpIcon.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js
- Adds keyboard accessibility to the upgrade to pro flow, missed in the previous PR. 
- Also fixes a small bug with the office selection UI, the collapsible years were not collapsing on click
=> WEB-3261: Keyboard accessiblility for upgrade to pro

app/(candidate)/dashboard/campaign-assistant/components/CampaignAssistantPage.js, app/(candidate)/dashboard/campaign-assistant/components/Chat.js, app/(candidate)/dashboard/campaign-assistant/components/ChatFeedback.js, app/(candidate)/dashboard/campaign-assistant/components/ChatHistory.js, app/(candidate)/dashboard/campaign-assistant/components/ChatInput.js, app/(candidate)/dashboard/campaign-assistant/components/CreateNewChat.js, app/(candidate)/dashboard/campaign-assistant/components/EmptyChat.js, app/(candidate)/dashboard/shared/DashboardLayout.js
Updates campaign assistant UI to the new design
Before:
After:
=> WEB-3277: Enhancement: Campaign Assistant Chat UI

app/(candidate)/dashboard/components/DashboardPage.js, app/(candidate)/dashboard/components/PrimaryResultModal.js, app/(candidate)/dashboard/page.js, app/(candidate)/dashboard/shared/DashboardLayout.js, helpers/objectHelper.js
Bug fix for DashboardPage re-opening the Primary Result modal after a user already submitted, but navigated back to the DashboardPage with the browser Back button
=> WEB-3260: Browser back button makes users reenter primary results

app/candidates/components/winners/WinnerFilters.js, app/candidates/components/winners/WinnerListSection.js
Fix for winners list filter, allows all filters to work together + makes button submit
=> fix: winners list filter

app/blog/article/[slug]/components/ArticleFaqs.js, app/blog/article/[slug]/components/BlogArticlePage.js, app/blog/article/[slug]/components/BlogAuthor.js, app/blog/shared/ShareBlog.js, app/shared/content/CmsContentWrapper.js, app/shared/typography/MarketingH2.js
Added data-testid tags for blog page elements
=> Added data-testid tags for blog page elements

.github/workflows/deploy.yml
This PR adds Playwright integration from https://github.com/thegoodparty/test-automation
=> Playwright Vercel Integration

app/(entrance)/set-password/components/ResetPasswordSuccess.js, app/(entrance)/set-password/components/SetPasswordPage.js, app/admin/users/components/Actions.js, app/admin/users/components/AddUserButton.js, app/admin/users/components/AdminUsersPage.js, app/admin/users/components/ResendPasswordEmailAction.js
- Sends a Set Password email after creating a new user with a Sales role.
-  <img width="914" alt="Screenshot 2024-11-15 at 11 47 13 AM" src="https://github.com/user-attachments/assets/5448c440-135c-420e-b042-d6e14130fedf">
- Also adds a button to Admin Users table to resend a set password email for Sales users only
- <img width="1704" alt="Screenshot 2024-11-15 at 11 49 29 AM" src="https://github.com/user-attachments/assets/e37b0957-4936-4a6b-b538-89345b406848">
- <img width="1707" alt="Screenshot 2024-11-15 at 11 49 35 AM" src="https://github.com/user-attachments/assets/fbb9c08a-72b0-46d6-8a9c-334d06e0674d">
=> WEB-3329: Enhancement: Admin - Sales user set password email

app/(entrance)/login/components/LoginPage.js, app/shared/inputs/EmailInput.js, app/shared/inputs/PasswrodInput.js
Added `data-testid` tags for the /login page:
- Email Input field
- Password Input field
- Forgot Password link
- Login submit button
=> Added data-testid tags for login page

.github/workflows/deploy.yml, app/(user)/profile/components/PersonalSection.js, app/candidates/components/Hero.js, app/candidates/components/map/CampaignPreview.js, app/candidates/page.js, app/homepage/Hero.js
=> Updated workflow file to run tests against qa for qa pushes (#369)

.github/workflows/deploy.yml
Updates deploy.yml to use GitHub Secrets for test credentials
.env file is being removed from `test-automation` repo for more security
=> Updates deploy.yml to use GitHub Secrets for test credentials

.github/workflows/deploy.yml
Added test pro account secret used in https://github.com/thegoodparty/test-automation/commit/7004eeaae2c8d7e596cf9916f44b2abdb68b6523
=> Added test pro account secret

.github/workflows/deploy.yml
Updated the YML file to send a Slack notification if tests fail; currently, the job ends if a failure is detected
=> Updated yml to send slack message upon failure

.github/workflows/deploy.yml
Updated Playwright Tests to run only for PRs to the QA branch, not pushes
=> Updated Playwright Test Conditions

.github/workflows/deploy.yml
Added Vercel install step to resolve recent deployment error:
```
Run vercel --token *** --yes
**mvercel --token *** --yes
shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/93e3baa4-674***-4a***3-8bac-***e3c06833ee3***sh: line ***: vercel: command not found
Error: Process completed with exit code ***[2](https://github.com/thegoodparty/gp-webapp/actions/runs/12661130402/job/35287676201#step:5:2)7***
```
=> Added Vercel install step

.github/workflows/deploy.yml
Updated Playwright YML to use admin credentials for admin tests, and to remove unneeded credential secrets (converted to account creation for nearly all tests)
=> Updated playwright yml

app/(candidate)/dashboard/pro-sign-up/purchase-redirect/components/PurchaseRedirectPage.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, app/(landing)/elections/[state]/[county]/[city]/page.js, app/(landing)/elections/[state]/[county]/page.js, app/(landing)/elections/[state]/page.js, app/(landing)/elections/components/FeaturedCities.js, app/(landing)/elections/position/[...loc]/page.js, app/(landing)/elections/shared/SearchLocation.js, app/shared/PaymentPortalButton.js, app/sitemaps/state/[state]/sitemap.js, gpApi/clientFetch.js, gpApi/index.js, gpApi/routes.js, helpers/fetchHelper.js
- Migrates races endpoints, ballotData/races, and payments endpoints
=> WEB-3606: Make the WebApp work with NestJS - Part 7 - Races, BallotData/Races, Payments

app/(landing)/elections/position/[...loc]/components/PositionSchema.js, app/(landing)/run-for-office/components/StartedBottom.js, app/candidate/[name]/[office]/components/CandidateSchema.js, app/layout.js, app/shared/layouts/GpHead.js, app/sitemaps/candidates/[state]/sitemap.js, app/sitemaps/sitemap.js, app/sitemaps/state/[state]/sitemap.js, appEnv.js, gpApi/clientFetch.js, gpApi/routes.js, helpers/handleApiRequestRewrite.js, middleware.js, pages/api/robots.js
This will simplify the front-end's url managements depending on environment deployment
=> [WEB-3367] - vercel configs

app/(candidate)/onboarding/[slug]/[step]/components/OfficeStepForm.js
Reverts thegoodparty/gp-webapp#462
=> Revert "Qa"

app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, middleware.js
Needs https://github.com/thegoodparty/gp-api/pull/96 to work
=> [WEB-3643] - Fixes validation error due to sending empty date string

app/serve/components/ServePage.js, app/serve/page.js, app/serve/shared/ServeLayout.js, app/serve/shared/ServeMenu.js, app/serve/shared/ServeMenuItem.js, app/shared/layouts/footer/Footer.js, app/shared/layouts/navigation/DashboardOrContinue.js, app/shared/layouts/navigation/LeftSide.js, app/shared/layouts/navigation/ProfileDropdown.js, app/shared/layouts/navigation/RightSide.js
=> feat: WEB-3619

app/candidates/components/map/Map.js, app/candidates/components/map/MapSection.js
campaign.position -> campaign.globalPosition
=> WEB-3721 Fix campaign map functions

app/blog/tag/[tag]/page.js, gpApi/routes.js
companion PR: https://github.com/thegoodparty/gp-api/pull/105
=> [WEB-3706]- Companion PR for https://github.com/thegoodparty/gp-api/pull/105

app/(candidate)/onboarding/[slug]/[step]/components/LegalStatements.js, app/faqs/[...titleId]/page.js, helpers/articleHelper.js
Some cleanup that was found during investigation for https://goodparty.atlassian.net/browse/WEB-3717
Companion API PR: https://github.com/thegoodparty/gp-api/pull/109
=> [WEB-3717] - faq urls

app/(company)/privacy/page.js, app/(company)/terms-of-service/page.js
Update calls to API for terms of service and privacy page to contentbytype and to access first index of the returned array
=> Web 3748 + Web-3747 - TOS and Privacy

app/(candidate)/dashboard/components/DashboardPage.js, app/(candidate)/dashboard/voter-records/[type]/components/ScheduleAddScriptFlow/ScheduleAddScriptFlow.js, app/(candidate)/dashboard/voter-records/[type]/components/ScheduleAddScriptFlow/SelectSmsAiTemplateScreen.js, app/(candidate)/dashboard/voter-records/[type]/components/ScheduleFlow.js
- fixes ai content categories not always loading in text campaign flow
- Also fixed another bug with the shape of the expected pathToVictory object on the dashboard page
=> WEB-3657: When scheduling text campaign I cannot generate a new script

app/(candidate)/dashboard/voter-records/[type]/components/BackToAllFiles.js, app/(candidate)/dashboard/voter-records/[type]/components/ReadMoreCard.js, app/(candidate)/dashboard/voter-records/[type]/components/ScriptCard.js, app/(candidate)/dashboard/voter-records/[type]/components/VendorCard.js
Add 'use client' header to files with event handlers
=> WEB-3754 Add 'use client' header to files with event handlers

app/political-terms/components/TermsHomePage.js, app/political-terms/page.js, app/shared/utils/ImageUpload.js
- fixes issue with user profile image upload not resetting state when a file is too large
- removes recent glossary items code
=> WEB-3736, WEB-3734

app/(candidate)/dashboard/campaign-assistant/components/ajaxActions.js
https://goodparty.atlassian.net/browse/WEB-3769
=> [WEB-3769] - ai chat feedback fix

app/shared/layouts/navigation/RightSideMobile.js
https://goodparty.atlassian.net/browse/WEB-3776
=> [WEB-3776] - fix short device login buttons

app/(user)/profile/components/PasswordSection.js
- Adds error message back into UI for Profile / Password section
=> WEB-3760: [NestJS] No error on incorrect password change

app/(entrance)/login/components/LoginPage.js, app/admin/users/components/AddUserButton.js, app/admin/users/components/AdminUsersPage.js, app/admin/users/components/ResendPasswordEmailAction.js, app/shared/layouts/navigation/FullStorySelectiveInit.js, app/shared/layouts/navigation/ProfileDropdown.js, app/shared/layouts/navigation/RightSide.js, helpers/permissionHelper.js, helpers/userHelper.js
- fixes some missed places that were still using the user.role field not treating roles as an array
=> WEB-3796: fix user role checks to account for array

app/(entrance)/set-password/components/FormSection.js, app/(entrance)/set-password/components/SetPasswordForm.js, app/(entrance)/set-password/components/SetPasswordPage.js, app/(entrance)/set-password/components/SetPasswordSuccess.js, helpers/fullStoryHelper.js
=> WEB-3778: simplified set password page

app/(entrance)/set-password/components/FormSection.js, app/(entrance)/set-password/components/ResetPasswordForm.js, app/(entrance)/set-password/components/ResetPasswordSuccess.js, app/(entrance)/set-password/components/SetPasswordPage.js, helpers/fullStoryHelper.js
Reverts thegoodparty/gp-webapp#513
=> Revert "WEB-3778: simplified set password page"

app/(entrance)/set-password/components/FormSection.js, app/(entrance)/set-password/components/SetPasswordForm.js, app/(entrance)/set-password/components/SetPasswordPage.js, app/(entrance)/set-password/components/SetPasswordSuccess.js, helpers/fullStoryHelper.js
Redo for: https://github.com/thegoodparty/gp-webapp/pull/513
=> WEB-3778: set password page updates

app/blog/article/[slug]/page.js, gpApi/apiFetch.js
https://goodparty.atlassian.net/browse/WEB-3829
companion API PR: https://github.com/thegoodparty/gp-api/pull/151
=> [WEB-3829] - blog 404s

app/(candidate)/dashboard/door-knocking/components/DoorKnockingPage.js, app/(candidate)/dashboard/door-knocking/components/InteractionsSummary.js, app/(candidate)/dashboard/door-knocking/page.js, app/(candidate)/dashboard/page.js, app/(candidate)/dashboard/shared/DashboardMenu.js, app/admin/ecanvasser/components/EcanvasserCard.js, utils/syncEcanvasser.js
=> Web 3846 ecanvasser sync

app/(entrance)/reset-password/components/ResetPasswordPage.js
- The reset password request was not properly handling errors, and always showing a success message
=> WEB-3854: Password Reset form broken

.github/workflows/e2e-tests.yml
=> [WEB-3851] - small cleanup, dump workflow event

app/admin/victory-path/[slug]/components/AdminVictoryPathPage.js, app/admin/victory-path/[slug]/constants/electionTypeChoices.const.js
- win number was not properly getting updated when it needed to be causing numbers from previous renders being used to calculate values and just being off
=> WEB-3885: fix out of sync calculation issues for admin victory path page

app/(candidate)/dashboard/shared/DashboardLayout.js, app/(candidate)/dashboard/tasks/components/TaskCheck.js, app/(candidate)/dashboard/tasks/components/TaskItem.js, app/(candidate)/dashboard/tasks/components/TasksPage.js, app/(candidate)/dashboard/tasks/page.js, gpApi/routes.js
This is this a WIP stage, this view can only be accessed by admins at `/dashboard/tasks` for now, until it is ready to replace the current dashboard front page
=> WEB-3888: Tasks frontend - Dashboard Tasks page scaffolded, Task Item components built

middleware.js
Link redirect from [goodparty.org/social](http://goodparty.org/social) to https://shor.by/goodpartyorg
specifically, I am copying the result of 
https://gp-api.goodparty.org/v1/content/type/redirects
into our redirects.
=> feat: redirects

app/(candidate)/dashboard/pro-sign-up/components/ProSignUpPage.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/components/ServiceAgreementPage.js
Backend PR: https://github.com/thegoodparty/gp-api/pull/223
ticket: https://goodparty.atlassian.net/browse/WEB-3690
=> feat: skip if verified

app/(user)/profile/components/SubscriptionPendingCancellationAlert.js
Companion API PR: https://github.com/thegoodparty/gp-api/pull/246
=> [WEB-3975] - Update cancellation message to support both auto cancel date and cancellation requested by user

app/(candidate)/onboarding/[slug]/[step]/components/OfficeStepForm.js, app/(candidate)/onboarding/shared/OnboardingLayout.js, app/shared/cards/CardPageWrapper.js, app/shared/layouts/CookiesSnackbar.js
https://goodparty.atlassian.net/browse/WEB-3942
=> [WEB-3942] - Makes cookie banner not block onboarding CTAs

app/(candidate)/dashboard/components/CampaignCountdown.js, app/(candidate)/dashboard/components/CampaignProgress.js, app/(candidate)/dashboard/components/RecordVoterContactsModal.js, app/(candidate)/dashboard/components/RemainingTasks.js, app/(candidate)/dashboard/components/VoterContactsCount.js, app/(candidate)/dashboard/shared/ProUpgradeModal.js, app/(candidate)/dashboard/tasks/components/CopyScriptButton.js, app/(candidate)/dashboard/tasks/components/LogTaskModal.js, app/(candidate)/dashboard/tasks/components/TaskCheck.js, app/(candidate)/dashboard/tasks/components/TaskItem.js, app/(candidate)/dashboard/tasks/components/TasksPage.js, app/(candidate)/dashboard/tasks/components/flows/AddScriptStep/AddScriptStep.js, app/(candidate)/dashboard/tasks/components/flows/AddScriptStep/GenerateReviewScreen.js, app/(candidate)/dashboard/tasks/components/flows/AddScriptStep/SelectSmsAiTemplateScreen.js, app/(candidate)/dashboard/tasks/components/flows/AudienceStep.js, app/(candidate)/dashboard/tasks/components/flows/CloseConfirmModal.js, app/(candidate)/dashboard/tasks/components/flows/DeadlineModal.js, app/(candidate)/dashboard/tasks/components/flows/DownloadStep.js, app/(candidate)/dashboard/tasks/components/flows/ImageStep.js, app/(candidate)/dashboard/tasks/components/flows/InstructionsStep.js, app/(candidate)/dashboard/tasks/components/flows/ScheduleStep.js, app/(candidate)/dashboard/tasks/components/flows/SocialPostStep.js, app/(candidate)/dashboard/tasks/components/flows/TaskFlow.js, app/(candidate)/dashboard/voter-records/[type]/components/DownloadFile.js, app/(candidate)/dashboard/voter-records/[type]/components/ScheduleCard.js, app/shared/typography/Subtitle2.js, helpers/voterFileDownload.js
- implements design review fixes, small bugfixes, code cleanup
- also adds Fullstory tracking attrs tasks ui
=> WEB-4000: design fixes, bug fixes, minor code cleanup

app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/OfficeStepForm.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CantFindRaceModal.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CustomOfficeForm.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/RaceCard.js, app/shared/buttons/Button.js, package-lock.json, package.json
https://goodparty.atlassian.net/browse/WEB-3943
Small API Companion PR: https://github.com/thegoodparty/gp-api/pull/249
=> [WEB-3943] - office picker improvements

app/(candidate)/dashboard/components/CampaignCountdown.js, app/(candidate)/dashboard/components/ContactCountsInfoModal.js, app/(candidate)/dashboard/components/DashboardHeader.js, app/(candidate)/dashboard/components/tasks/LogTaskModal.js, app/(candidate)/dashboard/components/tasks/TaskItem.js, app/(candidate)/dashboard/components/tasks/TasksList.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/ChooseScriptAddFlow.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/CreateSmSScriptScreen.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/GenerateLoadingScreen.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/GenerateReviewScreen.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/SelectSmSScriptScreen.js, app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/SelectSmsAiTemplateScreen.js, app/(candidate)/dashboard/components/tasks/flows/AudienceStep.js, app/(candidate)/dashboard/components/tasks/flows/ImageStep.js, app/(candidate)/dashboard/components/tasks/flows/InstructionsStep.js, app/(candidate)/dashboard/components/tasks/flows/ScheduleStep.js
Assorted design review UI cleanup + fixes: https://goodparty.atlassian.net/browse/WEB-4035
=> WEB-4035: Task dashboard UI fixes

app/shared/layouts/CookiesSnackbar.js
https://goodparty.atlassian.net/browse/WEB-3942?focusedCommentId=17075
=> [WEB-3942] - Design change request

app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CantFindRaceModal.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CustomOfficeForm.js
https://goodparty.atlassian.net/browse/WEB-3943?focusedCommentId=17144
=> [WEB-3943] - actionable Design changes

app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/BallotRaces.js
https://goodparty.atlassian.net/browse/WEB-3943?focusedCommentId=17272
=> [WEB-3943] - Bug Fix

app/political-terms/[slug]/page.js, app/political-terms/page.js, app/political-terms/util/glossaryItemFetching.util.js
https://goodparty.atlassian.net/browse/WEB-3789
=> [WEB-3789] - Ensures that /political-terms pages are SSG rendered and can be edge-cached

app/(entrance)/sign-up/components/SignUpPage.js, app/shared/inputs/RenderInputField.js
https://goodparty.atlassian.net/browse/WEB-3988
Companion API PR: https://github.com/thegoodparty/gp-api/pull/275
=> [WEB-3988] - Facilitated Signup

app/(landing)/elections/[state]/components/ElectionsStatePage.js, app/(landing)/elections/[state]/page.js, app/(landing)/elections/shared/fetchPlace.js, appEnv.js
Design looks a little scuffed, open to suggestions
Dependent on this election-api PR: https://github.com/thegoodparty/election-api/pull/31
=> WEB-4094 - children on state page are now categorized

app/layout.js, app/shared/scripts/RouteTrackerScript.js, app/shared/scripts/SegmentScript.js, appEnv.js
I removed the analytics.page() call from the end of the script to prevent it from double firing every time someone accesses a page on the first load. With this setup analytics.page() is only fired once
=> WEB:4083 - Add segment page tracking

app/candidate/[name]/[office]/components/AboutCard.js, app/candidate/[name]/[office]/components/ContentSection.js
=> chore: handle no about section

helpers/handleApiRequestRewrite.js
- previous fix i did broke the proxy rewrite when running webapp and api locally
=> fix proxy rewrite port

app/(candidate)/dashboard/voter-records/components/PaginationButtons.js, app/(candidate)/dashboard/voter-records/components/VoterRecordsPage.js
- adds simple text search and pagination to the voter file table 
Before:
After:
=> WEB-4179: add pagination and basic searching to voter file table

app/(candidate)/dashboard/pro-sign-up/committee-check/page.js, app/(candidate)/dashboard/pro-sign-up/page.js, app/(candidate)/dashboard/pro-sign-up/purchase-redirect/page.js, app/(candidate)/dashboard/pro-sign-up/service-agreement/page.js, app/(candidate)/dashboard/pro-sign-up/success/page.js, app/(candidate)/dashboard/shared/restrictDemoAccess.js, app/(candidate)/onboarding/shared/getCampaign.js, app/(user)/profile/page.js, app/admin/all-candidates/page.js, gpApi/serverFetch.js, helpers/userServerHelper.js
=> chore: make cookies call async

app/(candidate)/dashboard/website/editor/components/AddressAutocomplete.js, app/(candidate)/dashboard/website/editor/components/EditForm.js, app/(candidate)/dashboard/website/editor/components/IssuesForm.js, app/(candidate)/dashboard/website/editor/components/WebsitePreview.js, app/candidates/components/CandidatesPage.js
**Note: based on #714 that must be merged first**
=> WEB-4208: part 3 changes

app/(candidate)/dashboard/components/ContactCountsInfoModal.js
This text change is for the upcoming RaceTargetDetails data served from the election-api - https://github.com/thegoodparty/gp-api/pull/304
=> DT-122 - Update UI for new RaceTargetDetails (P2V) data

app/(candidate)/onboarding/[slug]/[step]/components/CompleteStep.js, app/(candidate)/onboarding/onboarding.consts.js, app/(candidate)/onboarding/shared/ajaxActions.js, app/(entrance)/login/components/LoginPage.js, app/(entrance)/set-name/components/SetNamePage.js, app/(entrance)/sign-up/components/SignUpPage.js, app/shared/utils/doLoginRedirect.js, app/shared/utils/handleDemoAccountDeletion.js, package-lock.json
https://goodparty.atlassian.net/browse/WEB-4324
Companion API PR: https://github.com/thegoodparty/gp-api/pull/332
=> [WEB-4324] - create campaign on register

app/(candidate)/dashboard/components/tasks/flows/ScheduleStep.js, app/(candidate)/dashboard/components/tasks/flows/util/flowHandlers.util.js
https://goodparty.atlassian.net/browse/WEB-4318
=> [WEB-4318] - Ensures that audienceRequest is included in resultant Slack message

app/(candidate)/dashboard/website/components/PublishedState.js, app/(candidate)/dashboard/website/components/StepList.js, app/(candidate)/dashboard/website/components/WebsiteInbox.js, app/(candidate)/dashboard/website/components/WebsiteVisits.js, app/(candidateWebsite)/c/[vanityPath]/components/WebsiteViewTracker.js, app/(candidateWebsite)/c/[vanityPath]/page.js, app/(candidateWebsite)/c/[vanityPath]/util/websiteTracking.js, app/shared/utils/ResponsiveModal.js, gpApi/routes.js
Implements basic visit tracking for candidate websites
=> WEB-4317 candidate website visit tracking

.gitignore, app/(user)/profile/components/ProfilePage.js, app/(user)/profile/components/texting-compliance/ComplianceStep.js, app/(user)/profile/components/texting-compliance/ComplianceSteps.js, app/(user)/profile/components/texting-compliance/TextingCompliance.js, app/(user)/profile/page.js, package-lock.json
https://goodparty.atlassian.net/browse/WEB-4341
https://www.figma.com/design/DnH9DcdB6HEM1nOJNFjL4V/P2P?node-id=4201-17231&m=dev
=> [WEB-4341] - Initial state of compliance flow

app/(candidate)/dashboard/website/create/components/WebsiteCreateFlow.js
okay this code was definitely removed, but i think it might have got back in with another PR
it was removed here: https://github.com/thegoodparty/gp-webapp/pull/778/files#diff-df23a57f291ab40c644e80d13bf 
third times the charm. just make sure when finishing the website workflow there is no modal to confirm in the final step before publishing
=> WEB-4375 remove code again, it may have snuck in with another PR

app/shared/layouts/navigation/NavigationProvider.js
Icon feedback and a quick fix for this issue: https://goodparty.atlassian.net/browse/WEB-4376
=> [WEB-4376] Nav update for URL, icons

app/(candidate)/dashboard/website/components/WebsiteInbox.js, app/(user)/profile/components/ProfilePage.js, app/(user)/profile/page.js, app/(user)/profile/texting-compliance/components/ComplianceSteps.js, app/(user)/profile/texting-compliance/components/TextingCompliance.js, app/admin/candidates/components/AdminCandidatesTable.js, app/admin/users/components/AdminUsersPage.js, helpers/numberHelper.js, package-lock.json
https://goodparty.atlassian.net/browse/WEB-4341
API companion PR: https://github.com/thegoodparty/gp-api/pull/370
=> [WEB-4341] - steps UI flow logic

app/(candidate)/dashboard/website/create/components/WebsiteCreateFlow.js, app/(candidate)/dashboard/website/editor/components/CompleteStep.js, app/(candidate)/dashboard/website/util/domainFetch.util.js
API PR: https://github.com/thegoodparty/gp-api/pull/376
=> chore: remove domain purchase if domain exists for the site

app/(candidate)/dashboard/components/RecordVoterContactsModal.js, app/(candidate)/dashboard/components/tasks/LogTaskModal.js, app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js, app/(candidate)/onboarding/[slug]/[step]/components/ballotOffices/CustomOfficeForm.js, app/(entrance)/login/components/LoginPage.js, app/(entrance)/login/components/SocialLoginButtons.js, app/(entrance)/sign-up/components/SignUpPage.js, app/shared/AmplitudeInit.js, app/shared/AnalyticsSessionReplayMiddleware.js, app/shared/layouts/navigation/SegmentIdentify.js, app/shared/scripts/RouteTrackerScript.js, app/shared/utils/analytics.js, helpers/analyticsHelper.js, helpers/segmentHelper.js, package-lock.json, package.json
=> fix: session recording

app/(candidate)/dashboard/purchase/components/PaymentInterstitials.js, app/(candidate)/dashboard/purchase/components/PurchaseHeader.js, app/(candidate)/dashboard/purchase/components/PurchaseIntentProvider.js, app/(candidate)/dashboard/purchase/components/PurchasePage.js, app/(candidate)/dashboard/purchase/components/PurchasePayment.js, app/(candidate)/dashboard/purchase/page.js, helpers/purchaseTypes.js, package-lock.json
https://goodparty.atlassian.net/browse/WEB-4469
=> [WEB-4469] - Refactors Stripe Elements implementation to be agnostic to be reusable for other features requiring purchase flows

app/admin/victory-path/[slug]/components/AdminVictoryPathPage.js
BE: https://github.com/thegoodparty/gp-api/pull/414
=> feat: add canDownloadFederal

app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js
=> Remove logging

app/(user)/profile/texting-compliance/register/components/TextingComplianceRegisterPage.js, app/(user)/profile/texting-compliance/register/components/TextingComplianceRegistrationForm.js, app/(user)/profile/texting-compliance/submit-pin/components/TextingComplianceSubmitPinForm.js, helpers/analyticsHelper.js
https://goodparty.atlassian.net/browse/WEB-4398
API companion PR: https://github.com/thegoodparty/gp-api/pull/457
=> [WEB-4398] - UI P2P Analytics events

app/(user)/profile/components/ProfilePage.js
https://goodparty.atlassian.net/browse/WEB-4548
=> [WEB-4548] - Removes isAdmin switch

app/(user)/profile/texting-compliance/register/components/TextingComplianceRegistrationForm.js
https://goodparty.atlassian.net/browse/WEB-4558
companion API PR: https://github.com/thegoodparty/gp-api/pull/476
=> [WEB-4558] - Allows for urls w/o protocol

app/(user)/profile/texting-compliance/register/components/TextingComplianceRegistrationForm.js, app/shared/AddressAutocomplete.js
[WEB-4557](https://goodparty.atlassian.net/browse/WEB-4557)
[WEB-4557]: https://goodparty.atlassian.net/browse/WEB-4557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-4557] - Marks fields as required

app/(user)/profile/texting-compliance/register/components/TextingComplianceRegistrationForm.js, app/shared/AddressAutocomplete.js
https://goodparty.atlassian.net/browse/WEB-4557?focusedCommentId=21695
=> [WEB-4557] - required fields
