- app/shared/utils/Tabs.js
> [WEB-1925] - Fixes hydration erros due to invalid-structured HTML

- app/(landing)/run-for-office/components/Hero.js
Small update to hero text on `/run-for-office` landing page.
Before: 
After:
> WEB-2716: Update headline on /Run-for-office

- app/candidate/[name]/[office]/components/CTA.js
Updates `claim` call to action button to link to `/run-for-office` instead of `/login`
> WEB-2637: Update link destinations on candidate pages

- app/blog/article/[slug]/components/BlogArticle.js
Small bugfix to remove extra callout banner at the top of Blog pages. 
Before:
After:
> WEB-2774: Double HiYa Banner on Blog article pages

- app/blog/article/[slug]/components/BlogArticle.js
- app/blog/shared/BlogWrapper.js
Fixes a few small issues with the new Blog pages:
- Ensures top-level category links are remain sorted by their defined orders
- Fixed spacing issues on header of Article pages to pull content above the fold.
Before:
After:
> WEB-2752: UI Fixes

- app/(candidate)/onboarding/[slug]/[step]/components/PartyStep.js
Small update for party options in onboarding flow, changed order and added a "Forward Party" option.
Before:
After:
> WEB-2813: Onboarding: Parties Update

- app/blog/article/[slug]/components/ArticleTags.js
Quick style fix for tag buttons at the bottom of an Article, they were overlapping each other when wrapped.
Before: 
After:
> fix: style fix for article tags wrapping

- app/(candidate)/dashboard/details/components/CampaignSection.js
This PR finishes up the remaining work for adding front end validation for the Campaign Website field on a candidate's details page `/dashboard/details`
This is a kind of messy way to handle it, but I didn't want to change more things than I needed to.
https://github.com/user-attachments/assets/d5a4330d-170d-45c8-85ad-10774155143b
> WEB-1838: Add frontend validation for Campaign Website field in My Details

- app/(landing)/run-for-office/components/KeyFeatures.js
- app/(landing)/run-for-office/components/Testimonials.js
- app/blog/article/[slug]/components/RelatedArticles.js
These were some small style fixes that came from demo feedback for the Run for Office page at the previous cycle demos. I had forgotten to push them up before I was out.
**Run for Office**
|Before|After|
|-|-|
|![BEFORE-goodparty org_run-for-office](https://github.com/user-attachments/assets/bb2e13bc-f637-421f-96fd-be1baddb523e)|![AFTER-localhost_4000_run-for-office](https://github.com/user-attachments/assets/2aae1eab-7553-45e3-aabf-e23435a52ccd)|
**Blog Article - Related Articles** 
Screenshot from `/blog/article/meet-lyn-leddy-independent-district-rockingham-24-nh`
|Before|After|
|-|-|
|<img width="1019" alt="Screenshot 2024-10-02 at 9 06 43 AM" src="https://github.com/user-attachments/assets/085242bc-5c11-4714-a8a2-71dbf72f939f">|<img width="1017" alt="Screenshot 2024-10-02 at 9 06 …
> WEB-3049: Run for Office page style fixes

- app/(candidate)/dashboard/components/ProSignUpAlert.js
Updated text on the upgrade account CTA at top of Dashboard .
Before:
After:
> WEB-2881: Enhancement: Banner Copy

- app/(candidate)/dashboard/components/p2v/PhasesModal.js
Added blog links to Dashboard Phases Modal.
Before:
After:
> WEB-2850: Enhancement: Blog Articles for Phases on Campaign Tracker

- app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js
- app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js
For [WEB-3091](https://goodparty.atlassian.net/browse/WEB-3091) Adds a toggle to the Pro Signup form to let a user skip entering an EIN number. For [WEB-3092](https://goodparty.atlassian.net/browse/WEB-3092) Adds a tooltip to the `Upload Campaign Filing Document` input.
Before:
After:
[WEB-3091]: https://goodparty.atlassian.net/browse/WEB-3091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3092]: https://goodparty.atlassian.net/browse/WEB-3092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEB-3091, WEB-3092: Upgrade to Pro form improvements

- app/(candidate)/dashboard/components/contactMethods/ContactMethodsSection.js
- app/(candidate)/dashboard/components/contactMethods/MethodRow.js
Adds a callout message underneath Texting in the Campaign Tracker's Voter Contact Methods section, depending on the User's Campaign viability
Before:
After:
> WEB-3090: Add a free texts message under Voter Contact Methods: texting

- vercel.json
Trying to increase `maxDuration` timeout for admin routes
> WEB-3119: try setting max duration for all /admin routes

- app/candidates/components/map/Map.js
Follow up on the earlier fix I did, this one should fix updating the URL search params when moving the map around, and the back button should properly work to step back through those changes
> Fix map history when moving around

- app/(candidate)/dashboard/voter-records/[type]/components/DownloadFile.js
- app/(candidate)/dashboard/voter-records/[type]/components/Hero.js
- app/(candidate)/dashboard/voter-records/[type]/components/VoterFileDetailPage.js
- app/(candidate)/dashboard/voter-records/components/CustomVoterAudienceFilters.js
- app/(candidate)/dashboard/voter-records/components/CustomVoterFile.js
- app/(candidate)/dashboard/voter-records/components/NeedHelp.js
- app/(candidate)/dashboard/voter-records/components/ViewAudienceFiltersModal.js
- app/(candidate)/dashboard/voter-records/components/VoterRecordsPage.js
Adds modals + buttons to let a user view their set audience filters for custom voter files.
Voter File List page:
Voter File Detail page:
> WEB-3208: Custom Voter File Settings saved and displayed.

- app/(candidate)/dashboard/voter-records/[type]/components/ScheduleAddScriptFlow/ScheduleAddScriptFlow.js
Callback was getting the event as the first arg instead of getting no arg
> WEB-3251: Clicking back from Add a Script breaks the text scheduling flow

- app/(candidate)/dashboard/voter-records/[type]/components/ScheduleFlow.js
- app/(candidate)/dashboard/voter-records/[type]/components/ScheduleFlowScheduleStep.js
- Fixes an issue in the Campaign Schedule flow where the close confirmation modal window opens when trying to close out of the scheduling flow after completing it.
- Also adds snackbar messages for success/error of the actual scheduling call
> WEB-3094: Prevent close confirmation from showing after a complete schedule

- app/candidates/components/Hero.js
- app/candidates/components/map/Map.js
- app/candidates/page.js
- app/homepage/Hero.js
- Reverts the winner counts to the dynamic number
- Adds `& Counting` to map header and tweaks the breakpoints
- Updates map to move to contain all campaign markers on first load
> Candidate Map Fixes

- .github/workflows/deploy.yml
Previously, test runs in TestRail were generating with the generic name "Playwright Test Run". 
With these changes in `deploy.yml` it will now generate with: 
"Playwright Test Run - Branch: ${{ github.ref_name }} - Commit: ${{ github.sha }}". 
This will make it easier to determine which branch/commit each test run is covering.
This also adds integrations with Slack to post test run results to #bot-test-automation
> Enable Slack notifications from TestRail, update test run titles

- app/candidates/components/map/Filters.js
- app/candidates/components/map/Results.js
- Updates the count of candidates on the map view to be fixed and not scroll with the result list
- Also updates the text a little: now shows # candidates with the total number of results. When viewing only a subset of the results in the map viewport, the text will read # candidates (# within view)
> WEB-3316: updated map result count to be fixed above scrolled content

- app/shared/buttons/ErrorButton.js
- app/shared/layouts/CookiesSnackbar.js
This PR adds `data-testid` tags for the cookie snackbar and cookie accept button.
Added for automation tests: https://github.com/thegoodparty/test-automation/pull/5
> Added data-testid tags for cookie snackbar

- .github/workflows/deploy.yml
- app/(user)/profile/components/PersonalSection.js
Added `data-testid` tags for the personal information section of the profile settings page.
Note: Since I could not sign-in locally or in a Vercel environment, I cannot not test these tags until it is pushed up to qa.goodparty.org
This PR also updates `deploy.yml` to run Playwright tests against pull requests to the `qa` branch
> Added data-testids for personal information in profile, updates deploy.yml

- app/candidates/components/Hero.js
- app/candidates/components/map/CampaignPreview.js
- app/candidates/page.js
- app/homepage/Hero.js
Requires this tgp-api change: https://github.com/thegoodparty/tgp-api/pull/311
- switches top level winner count number on homepage, candidate map to hardcoded number
- Adds primary result to candidate preview card over map if present
> WEB-3386: Update Candidate map count + add primary election result to preview

- .github/workflows/deploy.yml
Updated the Test Credential Secrets Names' to be more descriptive, as well as added additional test accounts:
- TEST_USER_ONBOARDING - User has not completed onboarding
- TEST_USER_LOCAL - User is running for a local office
- TEST_USER_STATE - User is running for a state office
- TEST_USER_FEDERAL - User is running for a federal office
- TEST_USER_DEMO_STATE - User is on the Demo (State)
- TEST_USER_DEMO_FEDERAL - User is on the Demo (Federal)
> Updated Test Credential Secrets Names

- .github/workflows/deploy.yml
- README.md
Currently, Slack only gets notified if tests all pass, this fix makes it so Slack will get notified for both passes and failures
> Added always() tag to slack notification yml step

- .github/workflows/deploy.yml
This PR updates the `deploy.yml` file to link the Vercel deployment to `gp-ui` instead of `gp-webapp`
> Updated deploy.yml to link Vercel deployment to gp-ui

- appEnv.js
`NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL` is usually set by vercel automatically, we are setting it manually on production to `https://goodparty.org`. We just need to remove the `https://` from the env var, and keep it here, so this still works the same on all envs
> fix: put https:// back in app base string

- app/sales/add-campaign/page.js
- app/shared/CreateCampaignForm.js
- Fixes an issue with the sales/admin campaign creation always giving the user a success message even if the call failed. 
- Adds more feedback to let user know that the call failed, and the error message to say why
- outputs some basic info of the created campaign for more feedback/validation
- Sends a success/error message to let the user know if the set password email sent or not
> WEB-3847: add feedaback to sales/admin add campaign page

- app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeCheckPage.js
- app/(candidate)/dashboard/pro-sign-up/committee-check/components/CommitteeSupportingFilesUpload.js
- app/(candidate)/dashboard/pro-sign-up/committee-check/components/EinCheckInput.js
- gpApi/index.js
- removed failing ein-check call for local client side validation 
- this was preventing users from continuing past the committee files upload step of the pro upgrade flow
> WEB-3870: Fix for users not able to upgrade

- app/(candidate)/dashboard/components/tasks/flows/AddScriptStep/GenerateLoadingScreen.js
- app/shared/hooks/CampaignProvider.js
- app/shared/layouts/PageWrapper.js
- helpers/fetchUserClientCampaign.js
- This is an issue with an out of sync campaign after firing off a content generation, the front end chooses the same number to append on the template name, so it is trying to generate a script with the same name.
- We are already polling the campaign to check the generation status, so the fix is to just use the campaign context hooks, to update the loaded campaign when polling
> WEB-3480: t will not let me generate two of the same type of script back-to-back

- app/(company)/volunteer/components/CTA.js
- app/(company)/volunteer/components/HelpWin.js
- app/shared/layouts/constants.js
- app/shared/layouts/navigation/NavigationProvider.js
- removes info session links from main navs
- updates links in /volunteer page to point to circle sign up
> WEB-4225: info session links

- app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js
- app/(candidate)/onboarding/[slug]/[step]/components/OnboardingPage.js
- app/(candidate)/onboarding/[slug]/[step]/page.js
- app/admin/victory-path/[slug]/components/AdminVictoryPathPage.js
- app/admin/victory-path/[slug]/components/VoterFileSection.js
- app/shared/CreateCampaignForm.js
- gpApi/routes.js
Mostly just resets to the previous commit, except for in cases where the district picker commit was not the most recent one. I left the actual district picker and supporting components in for re-use in possibly the admin or post pro - still to be decided by stakeholders.
Previous PR for adding the district picker: https://github.com/thegoodparty/gp-webapp/pull/756
All three flows (Onboarding, Add a Campaign, Admin Victory Path) work fine with these gp-api changes: https://github.com/thegoodparty/gp-webapp/pull/756
> WEB-4422 - Remove district picker, put dev in a releasable state

- app/(candidate)/dashboard/website/create/components/WebsiteCreateFlow.js
- app/(candidate)/dashboard/website/editor/components/WebsiteEditorPageStepper.js
**PR #875: chore: validate builder** - 
This pull request adds form validation to the website creation flow by implementing validation checks for title, email, phone, and address fields, importing validation helpers (`isValidEmail` and `isValidPhone`) and adding validation logic to handler functions that set the form's validity state based on user input, while also ensuring the "Publish website" button is properly disabled when validation fails by adding the `nextDisabled` condition to prevent users from proceeding with invalid data.
> chore: validate builder

- app/globals.css
- app/shared/AddressAutocomplete.js
Fixed the AddressAutocomplete component where the Google Places API dropdown was only visible on desktop but not on mobile devices. Added comprehensive CSS styles for `.pac-container` and `.pac-item` classes with mobile-specific media queries to ensure proper z-index layering, fixed positioning, and touch-friendly padding/font sizes. Enhanced the component with a MutationObserver to automatically apply mobile compatibility classes (`needsclick`) and touch-action properties to autocomplete containers for better touch event handling.
> fix: mobile autocomplete

- app/(candidate)/onboarding/[slug]/[step]/components/OfficeStep.js
Issue: The "Next" button on the office picker, in a minority of races <= 5%, would block the user for long periods of time, 5-10+ seconds. After running a bit of tracing down the call stack, the culprit was an LLM call that's made _before_ P2V is actually enqueued, for some reason
Solution: Remove the unnecessary await(s) on the frontend. This makes that next button advancement feel nearly instantaneous.
> DT-247 - Fix Long Blocking of Advancement - Removed unnecessary await

- app/(candidate)/dashboard/outreach/components/OutreachTable.js
Adds a Status column to the outreach table that displays status labels for text messaging campaigns.
- Frontend only: Added Status column to OutreachTable component
- Selective display: Status column only appears for outreachType === 'text'
- Graceful fallback: Shows "n/a" for non-text campaigns or invalid status
values
Maps backend status values to user-friendly labels per Figma:
- pending → "Draft"
- approved/denied → "In review"
- paid/in_progress → "Scheduled"
- completed → "Sent"
- Status field already exists in Outreach model
- API already returns status in responses
- No new data fields required - only presentation layer changes
> [WEB-4351] Add status column to outreach table for texting outreaches
